---
- name: Setup Ubuntu 22 development environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - ../../config.yml
  roles:
    # - _
    - system
    # - apache
    # - mariadb
    # - php
    # - phpmyadmin
    # - composer
    # - nodejs
    # - git
    # - user
